# Configure one or more display managers with a "best effort" approach.
---
displaymanagers:
  - lightdm

defaultDesktopEnvironment:
    executable: "cinnamon-session"
    desktopFile: "cinnamon"

basicSetup: false
sysconfigSetup: false
