---
# Whether to create /etc/machine-id for systemd.
systemd: true
# Whether to create /var/lib/dbus/machine-id for D-Bus.
dbus: true
# Whether /var/lib/dbus/machine-id should be a symlink to /etc/machine-id
symlink: true
# Whether to copy entropy from the host
entropy-copy: true
entropy-files:
    - /var/lib/urandom/random-seed
    - /var/lib/systemd/random-seed
