# Live-автологин для пользователя live-сессии GLDE.
# Удаляется при установке системы (Calamares shellprocess).
[Seat:*]
autologin-user=glde
autologin-user-timeout=0
user-session=cinnamon
greeter-session=slick-greeter
